trigger:
 - main

# pool:
# #    # vmImage: 'ubuntu-latest'
#   name: 'Drone'
resources:
- repo: self

steps:

# - script:
#     bash ./config-env.sh
#   displayName: 'Install linux dependencies'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'connect to docker'
#     repository: 'jmadupm/drone-repo'
#     command: buildAndPush
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'