trigger:
 - main

resources:
- repo: self

steps:
- script:
    bash ./config-env.sh
  displayName: 'Install linux dependencies'

- script:
    python3 ./src/main.py -n 10
  displayName: 'Execute test of the script'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'connect to docker'
#     repository: 'jmadupm/drone-repo'
#     command: buildAndPush
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'