trigger:
 - main

pool:
   vmImage: 'ubuntu-latest'
  # name: 'drone'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.9'
#   displayName: 'Use Python 3.9'

# - script:
#     sudo pkill -f "python3 main.py"
#   displayName: 'Stop current simulator'

- script:
    echo ${HOME}/drone-src
  displayName: 'Create app source'

- script:
    sudo apt -y install python3 python3-pip
  displayName: 'Install linux dependencies'

- script:
    pip3 install -r requirements.txt
  displayName: 'Install python packages'

- script:
    sudo cp -r . ${HOME}/drone-src
  displayName: 'Create app source'

# - script: 
#     python3 ./src/main.py &
# #   displayName: 'Execute new application'
# - task: PythonScript@0
#   inputs:
#     pythonInterpreter: 'python3'
#     scriptSource: 'filePath'
#     scriptPath: './src/main.py'