# number of devices to simulate
DEVICE_NUMBER = 5

# alarm values 
ALARM_HIGH_TEMPERATURE_C    = 42
ALARM_LOW_TEMPERATURE_C     = 10
ALARM_LOW_BATTERY_PERC      = 20 

# init values 
INIT_TEMPERATURE_C   = 26
INIT_HUMIDITY_PERC   = 80
INIT_BATTERY_PERC    = 100 
INIT_PRESSURE_KPa    = 100

# min values 
MIN_TEMPERATURE_C   = 10
MIN_HUMIDITY_PERC   = 40
MIN_BATTERY_PERC    = 0 
MIN_PRESSURE_KPa    = 80

# max values 
MAX_TEMPERATURE_C   = 50
MAX_HUMIDITY_PERC   = 100
MAX_BATTERY_PERC    = 100 
MAX_PRESSURE_KPa    = 120

# max values 
TEMPERATURE_VARIANCE    = 2
HUMIDITY_PERC_VARIANCE  = 2
BATTERY_PERC_VARIANCE   = 0.2 
PRESSURE_KPa_VARIANCE   = 2

ROUND_DECIMALS          = 1